"""update uuid field in user models

Revision ID: 59cce251df08
Revises: d56f82f4657c
Create Date: 2026-05-08 11:09:07.711337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59cce251df08'
down_revision: Union[str, Sequence[str], None] = 'd56f82f4657c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('user_role', sa.Enum('admin', 'user', 'staff', name='user_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_file', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_account_users_id'), 'account_users', ['id'], unique=False)
    op.create_index(op.f('ix_account_users_key'), 'account_users', ['key'], unique=True)
    op.create_table('account_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_account_posts_id'), 'account_posts', ['id'], unique=False)
    op.create_index(op.f('ix_account_posts_user_id'), 'account_posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_posts_user_id'), table_name='account_posts')
    op.drop_index(op.f('ix_account_posts_id'), table_name='account_posts')
    op.drop_table('account_posts')
    op.drop_index(op.f('ix_account_users_key'), table_name='account_users')
    op.drop_index(op.f('ix_account_users_id'), table_name='account_users')
    op.drop_table('account_users')
    # ### end Alembic commands ###
